### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by andreasleha** [eddelbuettel/rcpptoml#51] opened 2023-03-30 13:36 UTC
Trying to install the package I get

```
> install.packages("RcppTOML")
Installing package into ‘/home/aleha/R/4.2’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository NA/src/contrib:
  cannot open URL 'NA/src/contrib/PACKAGES'
trying URL 'https://cran.rstudio.com/src/contrib/RcppTOML_0.2.2.tar.gz'
Content type 'application/x-gzip' length 141195 bytes (137 KB)
==================================================
downloaded 137 KB

* installing *source* package ‘RcppTOML’ ...
** package ‘RcppTOML’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++17 -I"/opt/R/R-4.2.3.intel/include" -DNDEBUG -I../inst/include -DTOML_ENABLE_FLOAT16=0 -I'/home/aleha/R/4.2/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I"/opt/R/R-4.2.3.intel/include" -DNDEBUG -I../inst/include -DTOML_ENABLE_FLOAT16=0 -I'/home/aleha/R/4.2/Rcpp/include' -I/usr/local/include   -fpic  -g -O2  -c parse.cpp -o parse.o
g++ -std=gnu++17 -shared -L/opt/R/R-4.2.3.intel/lib -L/opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7 -L/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el7_9.x86_64/jre/lib/amd64/server -ljvm -L/usr/local/lib -L/home/aleha/local/lib -o RcppTOML.so RcppExports.o parse.o -L/opt/R/R-4.2.3.intel/lib -lR
installing to /home/aleha/R/4.2/00LOCK-RcppTOML/00new/RcppTOML/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘RcppTOML’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/aleha/R/4.2/00LOCK-RcppTOML/00new/RcppTOML/libs/RcppTOML.so':
  /home/aleha/R/4.2/00LOCK-RcppTOML/00new/RcppTOML/libs/RcppTOML.so: undefined symbol: _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/aleha/R/4.2/RcppTOML’

The downloaded source packages are in
	‘/tmp/RtmpE2a2jC/downloaded_packages’
Warning message:
In install.packages("RcppTOML") :
  installation of package ‘RcppTOML’ had non-zero exit status
```

This is on an older `CentOS Linux release 7.9.2009 (Core)` system with devtoolset-7.

(On this system there is an R-4.1.2 installation where RcppTOML in version 0.1.7 has been installed and now runs fine.)

**Comment by eddelbuettel** [comment] 2023-03-30 14:10
Duplicate of #47 and others.  Please search closed issues for "devtoolset".

If you cannot upgrade to a current compiler please do install an older version of RcppTOML.  They work too; but we now have a newer underlying library and it places demands on the compiler.

**Closed as completed by eddelbuettel** 2023-03-30 14:10 UTC
